version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - jekyll_cache:/srv/jekyll/.jekyll-cache
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_cache:
  bundle_cache: