version: '3.8'

services:
  googleauthtotpprototype:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./GoogleAuthTotpPrototype/app.db:/app/app.db
    depends_on:
      - db

  db:
    image: alpine:latest
    command: ["sh", "-c", "echo 'SQLite database will be created as a file in the app container'"]
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data: